// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sophia.Infrastructure.DbContext;

#nullable disable

namespace Sophia.Db.Migrations
{
    [DbContext(typeof(SophiaContext))]
    partial class SophiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sophia.Infrastructure.Models.AdminUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<string>("Emai")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("emai")
                        .HasComment("メールアドレス");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("名前");

                    b.Property<int>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("integer")
                        .HasColumnName("role")
                        .HasComment("ロール");

                    b.Property<int>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("ステータス");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id")
                        .HasName("pk_admin_user");

                    b.ToTable("admin_user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 2, 15, 8, 39, 29, 573, DateTimeKind.Utc).AddTicks(529),
                            Emai = "takada-yuki@new-world.local",
                            Name = "高田憂希",
                            Role = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 2, 15, 8, 39, 29, 573, DateTimeKind.Utc).AddTicks(793)
                        });
                });

            modelBuilder.Entity("Sophia.Infrastructure.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<string>("Emai")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("emai")
                        .HasComment("メールアドレス");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon_url")
                        .HasComment("アイコンURL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("名前");

                    b.Property<int>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("ステータス");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Emai")
                        .IsUnique()
                        .HasDatabaseName("ix_users_emai");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 2, 15, 8, 39, 29, 573, DateTimeKind.Utc).AddTicks(9227),
                            Emai = "aya-yamane@new-world.local",
                            IconUrl = "",
                            Name = "山根綺",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 2, 15, 8, 39, 29, 573, DateTimeKind.Utc).AddTicks(9490)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 2, 15, 8, 39, 29, 573, DateTimeKind.Utc).AddTicks(9743),
                            Emai = "kuwahara-yukinew-world.local",
                            IconUrl = "",
                            Name = "桑原由気",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 2, 15, 8, 39, 29, 573, DateTimeKind.Utc).AddTicks(9743)
                        });
                });

            modelBuilder.Entity("Sophia.Infrastructure.Models.UserDefinitiveRegisterToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at")
                        .HasComment("有効期限");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token")
                        .HasComment("トークン");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_definitive_register_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_definitive_register_token_user_id");

                    b.ToTable("user_definitive_register_token", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
